[package]
build = 'common/build/build.rs'
edition = '2021'
name = 'ton_node'
version = '0.55.35'

[workspace]
members = [ 'storage' ]

[dependencies]
arc-swap = '0.3.11'
async-recursion = '0.3.2'
async-trait = '0.1.22'
bitflags = '1.2.1'
chrono = '=0.4.19'
clap = '2.33.1'
colored = '1.9.3'
crossbeam-channel = '0.4.2'
dashmap = '5.4.0'
dirs = '2.0.2'
enum-as-inner = '=0.5.1'
env_logger = '0.7.1'
failure = '0.1'
futures = '0.3.1'
futures-timer = '3.0.1'
hex = '0.4'
lazy_static = '1.4.0'
log = '0.4'
log4rs = '1.2'
log4rs-rolling-file = '0.2.0'
num-bigint = '0.4'
num_cpus = '1.13'
openssl = '0.10.35'
rand = '0.7'
regex = '^1.3.0'
serde = '1.0.105'
serde_derive = '1.0.105'
serde_json = '1.0.64'
spin = '0.7.1'
stream-cancel = '0.8.0'
string-builder = '^0.2.0'
adnl = { features = [ 'client', 'node', 'server' ], git = 'https://github.com/tonlabs/ever-adnl.git', tag = '0.8.19' }
catchain = { path = 'catchain' }
ctrlc = { features = [ 'termination' ], version = '3.4.0' }
dht = { git = 'https://github.com/tonlabs/ever-dht.git', tag = '0.6.30' }
lockfree = { git = 'https://github.com/tonlabs/lockfree.git' }
overlay = { git = 'https://github.com/tonlabs/ever-overlay.git', tag = '0.6.210' }
rldp = { git = 'https://github.com/tonlabs/ever-rldp.git', tag = '0.7.205' }
statsd = { optional = true, version = '0.15' }
storage = { path = 'storage' }
tokio = { features = [ 'rt-multi-thread' ], version = '1.5' }
ton_abi = { git = 'https://github.com/tonlabs/ever-abi.git', optional = true, tag = '2.3.129' }
ton_api = { git = 'https://github.com/tonlabs/ever-tl.git', package = 'ton_api', tag = '0.3.24' }
ton_block = { git = 'https://github.com/tonlabs/ever-block.git', tag = '1.9.88' }
ton_block_json = { git = 'https://github.com/tonlabs/ever-block-json.git', tag = '0.7.168' }
ton_executor = { git = 'https://github.com/tonlabs/ever-executor.git', tag = '1.16.58' }
ton_types = { git = 'https://github.com/tonlabs/ever-types.git', tag = '2.0.18' }
ton_vm = { git = 'https://github.com/tonlabs/ever-vm.git', tag = '1.8.189' }
validator_session = { path = 'validator-session' }

[patch.'https://github.com/tonlabs/ever-vm.git']
ton_vm = { git = 'https://github.com/gosh-sh/ever-vm.git', branch = 'feature/gosh_hash_1.8.189' }

[features]
default = [ 'telemetry' ]
export_key = [ 'catchain/export_key', 'ton_types/export_key' ]
external_db = [ 'rdkafka' ]
gosh = [ 'ton_block/gosh', 'ton_vm/gosh' ]
metrics = [ 'statsd' ]
signature_with_id = [ 'ton_block/signature_with_id', 'ton_vm/signature_with_id', 'ton_executor/signature_with_id' ]
slashing = [ 'ton_abi', 'validator_session/slashing' ]
telemetry = [ 'adnl/telemetry', 'dht/telemetry', 'rldp/telemetry', 'overlay/telemetry', 'storage/telemetry' ]
trace_alloc = [  ]
trace_alloc_detail = [ 'trace_alloc' ]

[profile]


[target.'cfg(unix)'.dependencies.rdkafka]
optional = true
version = '0.26.0'

[target.'cfg(windows)'.dependencies.rdkafka]
features = [ 'cmake_build' ]
optional = true
version = '0.26.0'

